'use client'
import { useState } from 'react'

const services = [
  {
      id: 'development',
          title: 'Development',
              subtitle: 'Commercial real estate takes years to conceive, design, and finance',
                  content: `At still88, we specialize in transforming visionary concepts into stunning hotel properties that not only captivate guests but also drive profitability for owners and investors. Our comprehensive development services encompass every stage of the process, ensuring a seamless transition from initial idea to finished project.

                  We begin with meticulous site and asset selection, leveraging in-depth market analysis to identify the best opportunities for new developments or redevelopments of existing properties. Our team conducts thorough feasibility studies that assess market trends, demographic insights, and competitive landscapes, enabling informed decision-making right from the start.

                  Innovative architectural design is at the heart of our approach. We collaborate with leading architects and designers to create unique spaces that reflect both the essence of the brand and the needs of the target market.

                  Throughout the construction phase, we employ rigorous project management practices to oversee every detail, from budget adherence to timeline management. Sustainability is a core principle of our development philosophy—we prioritize eco-friendly practices and materials, ensuring our hotels minimize their environmental impact.`,
                    },
                      {
                          id: 'operations',
                              title: 'Operations',
                                  subtitle: 'Efficient Operations Transform Guests into Lifelong Patrons',
                                      content: `Efficient operations are the backbone of any successful hotel, and at still88, we pride ourselves on delivering exceptional operational management tailored to unique needs. Our dedicated team of seasoned professionals adopts a hands-on approach, meticulously overseeing daily operations to ensure that every aspect—from guest services and housekeeping to maintenance and dining—is executed with precision and care.

                                      We understand that the hospitality industry is constantly evolving, which is why we implement industry best practices and leverage advanced technology to streamline processes. By optimizing workflows and enhancing team performance, we create an environment that fosters both operational excellence and an outstanding guest experience.

                                      Training and development are at the core of our operations strategy. We believe that empowered staff members are key to delivering exceptional service. Our tailored training programs equip your team with the skills and knowledge necessary to exceed guest expectations.

                                      By integrating comprehensive performance metrics and regular assessments, we ensure that your hotel not only meets but exceeds industry standards.`,
                                        },
                                          {
                                              id: 'consulting',
                                                  title: 'Strategic Consulting',
                                                      subtitle: 'Strategic Insights That Drive Success in Hospitality',
                                                          content: `In today's rapidly evolving hospitality landscape, making informed decisions is crucial for long-term success. At still88, we provide expert guidance and strategic foresight through our comprehensive advisory and consulting services.

                                                          Our team offers the strategic insights and expertise needed to navigate market dynamics and capitalize on emerging trends. We conduct in-depth feasibility studies, financial modeling, and market analysis to assess potential projects and investments, ensuring you are well-prepared for the road ahead.

                                                          Our services include competitive benchmarking and tailored operational assessments that help identify growth opportunities and areas for improvement. With ongoing support in risk management, brand development, and market positioning, we empower you to stay competitive in a crowded marketplace.

                                                          Our seasoned consultants deliver actionable recommendations and innovative strategies, all backed by thorough research and industry knowledge.`,
                                                            },
                                                              {
                                                                  id: 'advisory',
                                                                      title: 'Expert Advisory Services',
                                                                          subtitle: 'Navigate Market Challenges with Expert Guidance',
                                                                              content: `In today's rapidly evolving hospitality landscape, making informed decisions is essential for long-term success. At still88, we offer expert testimony and litigation support, ensuring you have the strategic insights needed to navigate market dynamics and capitalize on emerging trends.

                                                                              Our services include:

                                                                              • Expert Testimony: Experienced professionals who deliver credible opinions based on thorough research and industry standards.

                                                                              • Asset Valuations: Comprehensive assessments for bankruptcy proceedings, partnership disputes, and market rent adjustments.

                                                                              • Quantification of Loss: Evaluating impacts from construction defects, operational disruptions, and more.

                                                                              In addition to litigation support, our advisory services encompass feasibility studies, financial modeling, and ongoing assistance in risk management and brand development. Trust still88 to guide you through complex challenges and achieve successful outcomes.`,
                                                                                },
                                                                                ]

                                                                                export default function Services() {
                                                                                  const [active, setActive] = useState('development')
                                                                                    const current = services.find(s => s.id === active)

                                                                                      return (
                                                                                          <>
                                                                                                {/* Hero */}
                                                                                                      <section className="bg-[#0a1628] py-32 px-6 text-center">
                                                                                                              <p className="text-[#c9a96e] text-sm tracking-widest uppercase mb-4">What We Do</p>
                                                                                                                      <h1 className="text-white text-4xl md:text-5xl font-playfair font-light">Our Services</h1>
                                                                                                                            </section>
                                                                                                                            
                                                                                                                                  {/* Intro */}
                                                                                                                                        <section className="py-20 px-6 bg-white">
                                                                                                                                                <div className="max-w-4xl mx-auto text-center">
                                                                                                                                                          <p className="text-gray-600 text-lg leading-relaxed">
                                                                                                                                                                      At still88, we recognize that clients have high expectations for the performance and potential of assets. With deep industry expertise and a commitment to deploying best practices across all facets of hotel management, we empower maximum returns and enhance guest satisfaction.
                                                                                                                                                                                </p>
                                                                                                                                                                                        </div>
                                                                                                                                                                                              </section>
                                                                                                                                                                                              
                                                                                                                                                                                                    {/* Tabs */}
                                                                                                                                                                                                          <section className="pb-24 px-6 bg-white">
                                                                                                                                                                                                                  <div className="max-w-6xl mx-auto">
                                                                                                                                                                                                                            {/* Tab Nav */}
                                                                                                                                                                                                                                      <div className="flex flex-wrap border-b border-gray-200 mb-12">
                                                                                                                                                                                                                                                  {services.map(s => (
                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                key={s.id}
                                                                                                                                                                                                                                                                                                onClick={() => setActive(s.id)}
                                                                                                                                                                                                                                                                                                                className={`px-6 py-4 text-sm tracking-wider uppercase font-medium transition-colors duration-200 ${
                                                                                                                                                                                                                                                                                                                                  active === s.id
                                                                                                                                                                                                                                                                                                                                                      ? 'text-[#c9a96e] border-b-2 border-[#c9a96e] -mb-px'
                                                                                                                                                                                                                                                                                                                                                                          : 'text-gray-500 hover:text-[#0a1628]'
                                                                                                                                                                                                                                                                                                                                                                                          }`}
                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                        {s.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Tab Content */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="grid md:grid-cols-2 gap-16 items-start">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-3xl font-playfair text-[#0a1628] mb-3">{current.title}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-[#c9a96e] text-sm tracking-wider uppercase mb-8">{current.subtitle}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="w-12 h-0.5 bg-[#c9a96e] mb-8" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {current.content.split('\n\n').map((para, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p key={i} className="text-gray-600 leading-relaxed mb-4 whitespace-pre-line">{para}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="bg-gray-50 p-10 border border-gray-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-[#c9a96e] text-xs tracking-widest uppercase mb-6">still88 Services</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ul className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {services.map(s => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li key={s.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => setActive(s.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className={`text-left w-full py-3 border-b border-gray-200 text-sm font-medium tracking-wide transition-colors ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                active === s.id ? 'text-[#c9a96e]' : 'text-gray-600 hover:text-[#0a1628]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {s.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mt-10 p-6 bg-[#0a1628]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-white text-sm mb-4">Ready to discuss your project?</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <a href="mailto:info@still88.com" className="text-[#c9a96e] text-sm tracking-wider hover:text-white transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    info@still88.com
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
