const currentHotels = [
  { name: 'Hampton Inn and Suites Trophy Club Fort Worth', brand: 'Hilton' },
    { name: 'Hampton Inn and Suites PVD Airport Warwick', brand: 'Hilton' },
    ]

    const pastHotels = [
      { name: 'Courtyard by Marriott Dallas', brand: 'Marriott' },
        { name: 'Embassy Suites Las Colinas Dallas', brand: 'Hilton' },
          { name: 'Homewood Suites by Hilton Dallas', brand: 'Hilton' },
            { name: 'TownePlace Suites by Marriott Dallas', brand: 'Marriott' },
              { name: 'Tryp By Wyndham College Station', brand: 'Wyndham' },
                { name: 'Wingate by Wyndham Dallas Las Colinas', brand: 'Wyndham' },
                  { name: 'Wingate by Wyndham Richardson Dallas', brand: 'Wyndham' },
                  ]

                  export default function Portfolio() {
                    return (
                        <>
                              <section className="bg-[#0a1628] py-32 px-6 text-center">
                                      <p className="text-[#c9a96e] text-sm tracking-widest uppercase mb-4">Track Record</p>
                                              <h1 className="text-white text-4xl md:text-5xl font-playfair font-light">Our Hotels</h1>
                                                    </section>

                                                          <section className="py-24 px-6 bg-white">
                                                                  <div className="max-w-5xl mx-auto">
                                                                            <div className="flex items-center gap-4 mb-12">
                                                                                        <div className="w-8 h-0.5 bg-[#c9a96e]" />
                                                                                                    <p className="text-[#c9a96e] text-sm tracking-widest uppercase">Current Portfolio</p>
                                                                                                              </div>
                                                                                                                        <div className="grid md:grid-cols-2 gap-6">
                                                                                                                                    {currentHotels.map(hotel => (
                                                                                                                                                  <div key={hotel.name} className="border border-gray-100 p-8 hover:border-[#c9a96e] transition-colors duration-300 group">
                                                                                                                                                                  <span className="text-xs tracking-widest text-[#c9a96e] uppercase mb-3 block">{hotel.brand}</span>
                                                                                                                                                                                  <h3 className="text-xl font-playfair text-[#0a1628] leading-tight">{hotel.name}</h3>
                                                                                                                                                                                                  <div className="w-6 h-0.5 bg-gray-200 group-hover:bg-[#c9a96e] mt-4 transition-colors duration-300" />
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          <section className="py-24 px-6 bg-gray-50">
                                                                                                                                                                                                                                                                  <div className="max-w-5xl mx-auto">
                                                                                                                                                                                                                                                                            <div className="flex items-center gap-4 mb-12">
                                                                                                                                                                                                                                                                                        <div className="w-8 h-0.5 bg-gray-400" />
                                                                                                                                                                                                                                                                                                    <p className="text-gray-500 text-sm tracking-widest uppercase">Past Portfolio</p>
                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                                                                                                                                                                                                                                                                                                                                    {pastHotels.map(hotel => (
                                                                                                                                                                                                                                                                                                                                                  <div key={hotel.name} className="bg-white border border-gray-100 p-6 hover:border-gray-300 transition-colors duration-300">
                                                                                                                                                                                                                                                                                                                                                                  <span className="text-xs tracking-widest text-gray-400 uppercase mb-2 block">{hotel.brand}</span>
                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-base font-medium text-[#0a1628] leading-snug">{hotel.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
